### ISSUE TITLE
Allow the setting of SecRequestBodyLimitAction through an environment variable

### ISSUE THREAD

**Issue by redRolf** [coreruleset/modsecurity-docker#100]
## The issue:
I am using ModSecurity as a proxy in front of a file server. Everything works fine in `DetectionOnly` mode. But as soon as I set `MODSEC_RULE_ENGINE=on`, the file upload fails.

With the following log message:
```
2022/01/15 15:45:13 [error] 30#30: *1 Request body limit is marked to reject the request, client: 1.1.1.1, server: domain.com, request: "PUT /public.php/webdav/ZAP_2.11.1.dmg HTTP/1.1", host: "domain.com"
2022/01/15 15:45:13 [error] 30#30: *1 client intended to send too large body: 222978300 bytes, client: 1.1.1.1, server: domain.com, request: "PUT /public.php/webdav/ZAP_2.11.1.dmg HTTP/1.1", host: "domain.com"
```

The reason for this is, that if `DetectionOnly` is set, the default for `SecRequestBodyLimitAction` is `ProcessPartial` and if `MODSEC_RULE_ENGINE=on` is set the default is for `SecRequestBodyLimitAction` is `Reject` which causes the file upload to fail as seen above.

## My request:
Make the [SecRequestBodyLimitAction in the modsecurity-override.conf](https://github.com/coreruleset/modsecurity-docker/blob/015bbe03eeb5270fa8097d282274902c6e7f4cb3/src/etc/modsecurity.d/modsecurity-override.conf#L25) configurable via ENV variable allowing me to set it in the Docker or Docker-Compose file.

This would prevent me from needing to overwrite your override.conf 😇

**Comment by fzipi** [comment]
Hi @redRolf ! Thanks for creating this one. I think we can do this with a sane default, sure.

**Comment by fzipi** [comment]
Oh, nice... looks like you already figured it out :) 

Will push a PR so you can test.

**Comment by fzipi** [comment]
Can you take a look at the linked PR?

**Comment by redRolf** [comment]
@fzipi the PR looks good to me 🚀

**Comment by fzipi** [comment]
This is good, will chain some other PRs and merged this today.
