### ISSUE TITLE
Can't start the container

### ISSUE THREAD

**Issue by gabibbo97** [coreruleset/modsecurity-docker#107]
Hello, I can't find a way to run the ModSecurity 3.3 NGINX Docker image

```
docker run --rm -it owasp/modsecurity-crs:3.3-nginx
2022/03/08 16:52:51 [emerg] 1#1: invalid parameter "${METRICS_ALLOW_FROM}" in /etc/nginx/includes/location_common.conf:10
nginx: [emerg] invalid parameter "${METRICS_ALLOW_FROM}" in /etc/nginx/includes/location_common.conf:10
```

Any tips?

**Comment by lonnie-smith** [comment]
This appears to be an issue with the `modsecurity-crs` nginx containers that were pushed to Dockerhub today

**Comment by fzipi** [comment]
Sorry about this, taking a look.

**Comment by fzipi** [comment]
Yeah, I figured that having templates where the config files live it is not a bad idea by now. I have a new change to move this to templates but still need to test it.

**Comment by fzipi** [comment]
Yes, this is a bug in the modsecurity-crs-docker image.

**Comment by fzipi** [comment]
@gabibbo97 The fix should be up when containers finish building! Thanks for reporting!
