### ISSUE TITLE
Host header modified in reverse proxy mode

### ISSUE THREAD

**Issue by alexHX12** [coreruleset/modsecurity-docker#109]
Hi, the Host header seems incorrect in reverse proxy mode, it always points to localhost independently from BACKEND value, so most website refuse this type of connection

I ran this command:
docker run -p 80:80 -e PROXY_SSL=on -e BACKEND=http://sitename imagename
![bug](https://user-images.githubusercontent.com/69585593/159104483-e38953fa-e040-4c70-a565-57e20dae6b27.png)

**Comment by theseion** [comment]
See my answer to your question on SO: https://stackoverflow.com/a/71536211/219324. Closing this issue.
