### ISSUE TITLE
Docker image for nginx rests on 1.20.2

### ISSUE THREAD

**Issue by 4soft-liebig** [coreruleset/modsecurity-docker#124]
Hi,

according to https://github.com/coreruleset/modsecurity-docker/blob/master/v3-nginx/Dockerfile#L1 the nginx-based modsecurity Docker image rests on nginx 1.20.2. According to https://nginx.org/en/download.html the latest stable version of nginx is 1.22.0.

Intially I came across this via openssl and a CVE that should be fixed in 1.1.1p. The openssl version in the latest modsecurity docker image is 1.1.1n. Should I bump the nginx version to 1.22.0 by myself (during the docker build)?

Best regards
Jörg Liebig

**Comment by fzipi** [comment]
Hi @4soft-liebig!

Does the image contain the fix already? I mean, it might depend on the base image instead of the nginx one, right? Also, are you using the alpine variant?

**Comment by 4soft-liebig** [comment]
Hi,

thanks for the fast response. I checked the dependency chain:

1. owasp/modsecurity:3.0.7 (https://github.com/coreruleset/modsecurity-docker/blob/master/v3-nginx/Dockerfile#L1)
2. nginx:1.20.2 (https://hub.docker.com/layers/nginx/library/nginx/1.20.2/images/sha256-a76df3b4f1478766631c794de7ff466aca466f995fd5bb216bb9643a3dd2a6bb?context=explore and https://github.com/nginxinc/docker-nginx/blob/d4a47bc6602d3a1412dad48a8513b83805605ef3/stable/debian/Dockerfile using 1.22.0, since Dockerfiles are generated.)
3. debian:bullseye-slim (https://hub.docker.com/layers/debian/library/debian/bullseye-slim/images/sha256-d2285c63f42a27d633afa75929529c3761883faac292e7c1cf310d91c7399863?context=explore)

I'm not sure where openssl actually comes from. Since I don't see it in the respective Dockerfiles. What can I do?

**Comment by 4soft-liebig** [comment]
Hi,

looking at the relevant CVE documentation at openssl (see https://www.openssl.org/news/secadv/20220705.txt), reveals that we are not affected (only 32bit is affected) and -- I'm guessing -- that is why there is no security update.

jl
