### ISSUE TITLE
Things Needed For Docker

### ISSUE THREAD

**Issue by danehrlich1** [coreruleset/modsecurity-docker#15]
This container is going to be run as a reverse proxy basically.

It should:
- SSL CERT: generate its own self-signed SSL cert to accept TLS traffic. User can replace with their own SSL cert after it is up and running if they want
- HIGHER VERSION: we should build Apache from source so we get 2.4.38 which has quite a bit more than 2.4.29, the latest version in Ubuntu:18.04 LTS 
- DEFAULT SITE FILE: we should add in a default site file that sets up the correct ProxyPass directives. The IP address to pass the requests too will be a variable the user will provide on the command-line during `docker run`.
- DOCKERFILE SECURITY: we can probably put some limits on the container by dropping certain kernel privileges, restricting resource consumption, etc. There are some easy/quick commands to do this 
- RANDOM: random other things I'm forgetting :)

Future Cool Stuff:
- We can make a [helm chart](https://helm.sh/) for ModSecurity!
- This helm chart could be used to install ModSecurity firewall layer on any K8s cluster...going to be cool stuff

**Comment by fzipi** [comment]
For SSL CERT, should we add https://github.com/icing/mod_md so we can generate also valid certificates using LetsEncrypt?

**Comment by franbuehler** [comment]
We should also add automated builds. The current images are 4 and 6 months old.
That's not  very trustworthy.

**Comment by danehrlich1** [comment]
> For SSL CERT, should we add https://github.com/icing/mod_md so we can generate also valid certificates using LetsEncrypt?

Yes very good point.

**Comment by csanders-git** [comment]
hmmm, you think its not a drag on the letsencrypt echosystem?>

**Comment by fzipi** [comment]
The only thing is if this is a public facing IP or not. Otherwise, it won't work.
Also `httpd:2.4` doesn't come with `mod_md` by default, so we may delay this plan a little bit.

**Comment by fzipi** [comment]
@danehrlich1 This one is > 2 years old, lots of things have changed by now. Do you think you can create a new issue with the remaining stuff you'll like to see? I'm closing this one.
