### ISSUE TITLE
Docker image uses the root user

### ISSUE THREAD

**Issue by duhlin** [coreruleset/modsecurity-docker#163]
Do you consider moving the base docker images for docker and apache to 'unprivileged' images, i.e. images not running with root user by default ?
This could be achieved for nginx using a [different base image](https://hub.docker.com/r/nginxinc/nginx-unprivileged) or by changing the default permissions of some folders/files.

**Comment by fzipi** [comment]
We have this in our backlog. See related issue https://github.com/coreruleset/modsecurity-crs-docker/issues/55.

**Comment by duhlin** [comment]
Thanks, I've missed that. We can close this issue then...
