### ISSUE TITLE
⚠️ This repository is going to be merged into the modsecurity-crs-docker repo

### ISSUE THREAD

**Issue by fzipi** [coreruleset/modsecurity-docker#164]
## Rationale

While creating new functionality, and when users are reporting problems, it is somehow difficult to know which repo to use. Also, maintaining both sets of containers doesn't make too much sense now, as most of our users are getting the modsecurity-crs container.

## Decision

The decision during retreat to let go of the naked ModSec container and to concentrate on a CRS container.

## Timing

We are going to start working on this merge and let all the users known.

**Comment by theseion** [comment]
How should we proceed? Suggestion:
1. Add banner to README now
2. Archive project now
3. perform the merge (in a couple of days)

**Comment by fzipi** [comment]
Yes, we should add the banner and point everything the the other repo. After that we can archive.

I've already started working on the merge PR.

**Comment by fzipi** [comment]
Issues should be moved to the other repo also.

**Comment by fzipi** [comment]
Issues transferred.

**Comment by fzipi** [comment]
Merged was done, and tests were performed to verify we provide the same features. See https://github.com/coreruleset/modsecurity-crs-docker/issues/102.
