### ISSUE TITLE
Post Images to GCR

### ISSUE THREAD

**Issue by danehrlich1** [coreruleset/modsecurity-docker#22]
Our Docker images should also be posted Google Container Registry:

1. GCR does automated vuln analysis. For instance the current container image has 329 vulns, with 5 of them being pretty serious: https://gcr.io/crs-support/modsecurity-docker/v3/apache-apache

2. GCR can be secured with 2FA by the admins, which for some reason Docker Hub does not have

3. For the base image, we can you GCP Managed Based Images, which are pretty hardened / secured: https://cloud.google.com/container-registry/docs/managed-base-images

4. We can link GCR to Github in a variety of ways, such that when new code is pushed to Github, if it has a tag on it it can kick off a build of the image in GCR. If we want can also send to Cloud Build for testing...

**Comment by fzipi** [comment]
@danehrlich1 Is this something desirable still?
