### ISSUE TITLE
No Graceful Shutdown for Apache

### ISSUE THREAD

**Issue by srueg** [coreruleset/modsecurity-docker#39]
Unfortunately since we use the `apachectl -D FOREGROUND` command to start Apache, the SIGTERM will only stop the `apachectl` process which won't relay it to the actual Apache process. This means that in a typical container environment, the SIGTERM is sent, `apachectl` is terminated but apache remains running in the background. Once the timeout (i.e. ca. 30s) is over, the apache process will be forcefully killed (by `SIGKILL`) which prevents any graceful shutdown.

We could solve this in an entrypoint script which traps the `SIGTERM` signal and then calls `apachectl graceful-stop`.

**Comment by fzipi** [comment]
We are using httpd-foreground from upstream now, so closing this one.
