### ISSUE TITLE
AuditLog in JSON

### ISSUE THREAD

**Issue by linkos82** [coreruleset/modsecurity-docker#42]
Hi,

We are using 3.0.4 image and we can not configure format logs in JSON :
SecAuditLogFormat JSON

{"error":"ModSecurity was not compiled with JSON support."}

Are you going to fix that ?

Thanks for the reply

**Comment by bittner** [comment]
Is your problem specific to the [owasp/modsecurity](https://hub.docker.com/r/owasp/modsecurity/) Docker image? If yes, which tag?

If not, you may want to ask at [SpiderLabs/ModSecurity](https://github.com/SpiderLabs/ModSecurity) for help. Also, describe your problem in a step-by-step fashion, so it's easier to reproduce.

**Comment by linkos82** [comment]
Hi @bittner ,

Yes, it is specific to the owasp/modsecurity Docker image, we are using the tag 3.0.4 for nginx.
Detected rules are sent to auditlog.
In modsecurity.conf :
SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLogParts ABIJDEFHZ
SecAuditLogType Serial
SecAuditLog /var/log/modsec_audit.log

If we want modsec_audit.log in JSON format we need to add :
SecAuditLogFormat JSON

But when we reload nginx and test with JSON format, here is the error in modsec_audit.log :
{"error":"ModSecurity was not compiled with JSON support."}

It appears that modsecurity needs to be recompiled with the the YAJL library components.

https://github.com/SpiderLabs/ModSecurity/issues/2116 

Regards,

**Comment by bittner** [comment]
According to the issue you linked, ModSecurity needs to be built with the YAJL library components. This [is the case in the implementation](https://github.com/CRS-support/modsecurity-docker/blob/master/v3-nginx/Dockerfile#L30-L46) we currently maintain.

Have you tried the `owasp/modsecurity:nginx` image (should be identical to `owasp/modsecurity:3.0.4`)? Can you please post the exact commands you run, so your problem can be reproduced on a clean developer machine?

**Comment by codeguy** [comment]
I'm using the `owasp/modsecurity:3.0.4` image and it does not output JSON when configured to do so. I don't see any errors in the logs though.

**Comment by Chivolta** [comment]
Same situation with owasp/modsecurity-crs:nginx

**Comment by fzipi** [comment]
I can confirm that last versions for this image are working with JSON logs by default.

```
❯ docker run -p 8080:80 owasp/modsecurity:nginx
2021/06/24 13:23:14 [notice] 1#1: ModSecurity-nginx v1.0.2 (rules loaded inline/local/remote: 0/6/0)
..
❯ curl localhost:8080/test\?value=/etc/passwd
...
172.17.0.1 - - [24/Jun/2021:13:21:53 +0000] "GET /test?value=/etc/passwd HTTP/1.1" 502 494 "-" "curl/7.64.1" "-"
{"transaction":{"client_ip":"172.17.0.1","time_stamp":"Thu Jun 24 13:21:53 2021","server_id":"df696acbce2ee39390794ca60e5263b7affd4ca3","client_port":63570,"host_ip":"172.17.0.2","host_port":80,"unique_id":"162454091348.031195","request":{"method":"GET","http_version":1.1,"uri":"/test?value=/etc/passwd","headers":{"Host":"localhost:8080","User-Agent":"curl/7.64.1","Accept":"*/*"}},"response":{"body":"<!DOCTYPE html>\n<html>\n<head>\n<title>Error</title>\n<style>\n    body {\n        width: 35em;\n        margin: 0 auto;\n        font-family: Tahoma, Verdana, Arial, sans-serif;\n    }\n</style>\n</head>\n<body>\n<h1>An error occurred.</h1>\n<p>Sorry, the page you are looking for is currently unavailable.<br/>\nPlease try again later.</p>\n<p>If you are the system administrator of this resource then you should check\nthe error log for details.</p>\n<p><em>Faithfully yours, nginx.</em></p>\n</body>\n</html>\n","http_code":502,"headers":{"Server":"nginx/1.20.1","Date":"Thu, 24 Jun 2021 13:21:53 GMT","Content-Length":"494","Content-Type":"text/html","Connection":"keep-alive","ETag":"\"60acef1a-1ee\""}},"producer":{"modsecurity":"ModSecurity v3.0.4 (Linux)","connector":"ModSecurity-nginx v1.0.2","secrules_engine":"Enabled","components":[]},"messages":[]}}
```
