### ISSUE TITLE
Add dependabot to bump base dependencies automatically

### ISSUE THREAD

**Issue by fzipi** [coreruleset/modsecurity-docker#46]
We should use https://dependabot.com/docker/ to update dependencies on base images, so we can speed up the process.

**Comment by franbuehler** [comment]
Hi @fzipi 

Can't we just activate Dependabot via Settings -> Security&analysis -> Dependabot alerts -> Enable??
Unfortunately I do not have the permissions.

**Comment by fzipi** [comment]
Done.
