### ISSUE TITLE
error opening output file: Read-only file system - owasp/modsecurity:3.0.4

### ISSUE THREAD

**Issue by xenorites** [coreruleset/modsecurity-docker#48]
Whenever I attempt to run the owasp/modsecurity:3.0.4 image, the only output I get from it is `error opening output file: Read-only file system`. All other containers I attempt to run work fine, including owasp/modsecurity:3.0.3.

**Comment by pdonnelly** [comment]
So I realize this is from months ago but just in case you or anyone else is still dealing with this, I ran into this as well. 

At least in my case, I was using docker to mount a custom nginx default.conf file as a read-only mount. The docker-entrypoint.sh script tries to update this file (and a few others) with the environment variables specified in the readme. But when it gets to the default.conf file it's read-only and throws that error message. 

Making the default.conf file read-write solved this issue for me.

**Comment by fzipi** [comment]
Thanks for testing, closing this one.
