### ISSUE TITLE
Switching to owasp/modsecurity:nginx - unable to audit log to file

### ISSUE THREAD

**Issue by dosera** [coreruleset/modsecurity-docker#51]
Hi everyone, after switching from `owasp/modsecurity:3-nginx` to `owasp/modsecurity:nginx` modsecurity seems to be unable to log anything to audit log (configuration didn't change at all).

nginx.conf:
```
modsecurity on;
modsecurity_rules_file /etc/modsecurity.d/include.conf;
```

include.conf:

```
Include /etc/modsecurity.d/modsecurity.conf
Include /etc/modsecurity.d/crs-setup.conf
Include /etc/modsecurity.d/rules.d/*.conf
```

modsecurity.conf:
```
SecRuleEngine DetectionOnly
...
SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLogParts ABIJDEFHZ
SecAuditLogFormat JSON
SecAuditLogType Serial
SecAuditLog /var/log/modsecurity/modsec_audit.log
..
```

crs-setup.conf
```
SecDefaultAction "phase:1,log,auditlog,pass"
SecDefaultAction "phase:2,log,auditlog,pass"
```

I noticed that compared to `owasp/modsecurity:3-nginx` a lot of envs are set in `owasp/modsecurity:nginx`, e.g.
```
MODSEC_AUDIT_LOG=/dev/stdout
MODSEC_AUDIT_LOG_FORMAT=JSON
MODSEC_AUDIT_LOG_TYPE=Serial
MODSEC_AUDIT_STORAGE=/var/log/modsecurity/audit/
..
```

Would those be preferred over the defined values in the modsecurity.conf? Didn't find any information on this anywhere.
Yet even after unsetting all of those and making the environment the same as in `owasp/modsecurity:3-nginx`  doesn't help.
Any input is much appreciated!

**Comment by bittner** [comment]
Yes, the environment variables should make it easier to run the container image in a cloud-native setup (e.g. with Kubernetes, but also without). See the [README](https://github.com/coreruleset/modsecurity-docker#how-to-use-this-image) for an explanation of all of them.

Let us know if you find this hard to use, and what your expectations on an easy, yet modern setup are.

**Comment by dosera** [comment]
Thanks for your reply  - I read the README regarding them and think its good to use; yet I am wondering what takes precedence - envs or values in configurations.

Regarding the empty log file issue: Interestingly enough I deploy it to another host and there it works flawlessly as before - therefore I am more confused than before.

**Comment by bittner** [comment]
The env variables are simply placeholder values with defaults, as documented. If you override or overwrite a configuration file that replaces or excludes the configuration files shipped with the image then your configuration takes over. There is no magic. It should be straight-forward to understand.

Also note that the new images are based on the official Apache and Nginx images, so the directory layout may have changed.

**Comment by dosera** [comment]
Good to know, thanks. Makes sense.
Yes - I overwrite them with my volumes, no issues there.
Yet I am still wondering why nothing gets written to my JSON log and how to debug this (did debug level 9 but cant seem to find anything pointing me in the direction).

**Comment by dosera** [comment]
Closing this as it is working on a different VM.
Assuming it was an issue on my side.

Thanks for the help!
