### ISSUE TITLE
Nginx.conf is empty during multiple POD deployments

### ISSUE THREAD

**Issue by ltoinel** [coreruleset/modsecurity-docker#52]
Hi,

Our Nginx.conf is externalized from our Docker images.

This file is sometimes empty after multiple POD start simultaneously.

The issue seems to come from the following lines in the entrypoint.sh : 
``
for FILE in ${FILES[*]}; do
    if [ -f $FILE ]; then
        envsubst "$ENV_VARIABLES" <$FILE | sponge $FILE
    fi
done
``

An empty Stdout seems to be send to the sponge command that produce an empty nginx file.

Do you have already saw this behaviour on your environnements ?

**Comment by bittner** [comment]
I don't understand the role of "sometimes" and "after multiple Pods start simultaneously".

I do see that [the line you quote](https://github.com/coreruleset/modsecurity-docker/blob/master/v3-nginx/docker-entrypoint.sh#L14-L18) has improvement potential (complex redirection is a beast). But why does it fail only "sometimes"?

Could you prepare a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand the problem? An open source repository or code snippet would be ideal.

**Comment by fzipi** [comment]
@ltoinel Care to comment here, or do we close this one?
