### ISSUE TITLE
As of ModSecurity version 3.0, SecTmpDir is no longer supported

### ISSUE THREAD

**Issue by daberlin** [coreruleset/modsecurity-docker#61]
That's what the doc says.
The parser seems to agree:
https://github.com/SpiderLabs/ModSecurity/blob/4127c1bf52d2b30a5c2c3e641b8085fd9a720f43/src/parser/seclang-parser.yy#L1674

So does it make sense to set it in the config?

**Comment by fzipi** [comment]
Per comment in the code:
```
/* Parser error disabled to avoid breaking default installations with modsecurity.conf-recommended
```

While it would not break v3 installations, I agree to just remove it with a deprecation warning.

**Comment by fzipi** [comment]
@daberlin After creating a new PR, we reviewed the documentation and it is indeed needed for v2. So for the sake of simplicity (one config file), let's leave it there.
