### ISSUE TITLE
 owasp/modsecurity:3-nginx proxy-cache not working

### ISSUE THREAD

**Issue by Oah433** [coreruleset/modsecurity-docker#63]
" owasp/modsecurity:3-nginx" when used with the caching directive, the whole thing stops to work. 
Tried the default one:
proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=edge-cache:10m inactive=60m max_size=1g use_temp_path=off;

Thought it was a root privilege problem so tried following folder which is owned by nginx:     
proxy_cache_path  /var/log/nginx levels=1:2 keys_zone=edge-cache:10m inactive=60m max_size=1g use_temp_path=off;
Still to no vail.

I suggest changing the owner-ship of /var/cache/nginx to the user->nginx.

Even tried to change the user from nginx to root in the configuration file but still didn't work. 
#user  nginx;
user root;
worker_processes  auto;

**The same problem occurs when using rate-limiting:**
limit_req_zone $remote_addr zone=rate_limit1:12m rate=5r/m;

I think its is permission related issue.

**Comment by fzipi** [comment]
@Oah433 Let me get the problem clear: after changing the directory permissions, things started working?

**Comment by fzipi** [comment]
No answer, closing.
