### ISSUE TITLE
New images only built with architecture: `arm`

### ISSUE THREAD

**Issue by jamesmeneghello** [coreruleset/modsecurity-docker#83]
New images published to DockerHub (3.0.5 / 3.0 / 3) are only published as `arm` images, breaking any dependent containers using `amd64`. Any chance of including the other architectures?

**Comment by fzipi** [comment]
@jamesmeneghello Thanks for filing. Looks like indeed that's what is happening. I'm actively tracking this one.

**Comment by fzipi** [comment]
I think that this happens because of the gha matrix builds. Will change to use platforms in one step.

**Comment by fzipi** [comment]
@jamesmeneghello Things look better now:
![image](https://user-images.githubusercontent.com/3012076/134241274-9672c735-3325-4617-b2e0-3bc9511f35f4.png)

**Comment by fzipi** [comment]
I think that this happens because of the gha matrix builds. Will change to use platforms in one step.
