### ISSUE TITLE
It would be realy helpfull, if the README.md gave an overview of the accepted .env variables

### ISSUE THREAD

**Issue by redRolf** [coreruleset/modsecurity-docker#94]
In the [README.md](https://github.com/coreruleset/modsecurity-docker/blob/d8bab0b4b72ec8f5afa1828ff3368ecc4c80b3a1/README.md) only the default env values are mentioned. This is not very useful, as there is no mention of what values are accepted. 

A list of all possible env values should be given.

**Comment by fzipi** [comment]
Hi @redRolf ! I'm trying to understand what you are trying to get here.

There are three different sections in the README file: one for the Apache vars, another for Nginx vars, and the last for ModSecurity vars. Can you give me an example of what you will expect from those? I mean... that's the whole list of possible env values.

**Comment by redRolf** [comment]
Hi @fzipi I do apologise for the bad quality of my issue. Thank you for your quick response. The section I am referencing is the [ModSecurity ENV Variables](https://github.com/coreruleset/modsecurity-docker/blob/d8bab0b4b72ec8f5afa1828ff3368ecc4c80b3a1/README.md#modsecurity-env-variables) I found myself repeatedly wondering what values are accepted. There are some that are obvious like directory paths. But there are others where I then had to do research on what values are accepted. Here are some examples:

* MODSEC_AUDIT_LOG_FORMAT (Default: JSON), the other accepted value here is `Native` but there is no way for me to know this.
* MODSEC_AUDIT_ENGINE (RelevantOnly), here it would be good to know, what is relevant only means and what other values are accepted here. 
* MODSEC_RULE_ENGINE (Default: on), here the values `DetectionOnly` and `off` are also accepted, where the latter is trivial but `DetectionOnly` is not.

It would be great to have either just a list of the accepted values. This would make it more comprehensive and not put me in the position where I need to start looking elsewhere for an explanation of what values are accepted. 

If a list or documentation does exist, it would also work for me if you just linked that documentation.

**Comment by fzipi** [comment]
Now, that makes more sense :)

Truly sorry, probably we are way too used to the config of modsecurity to describe those, but you make a perfectly valid point. Will extend the readme with values and pointers to the modsecurity wiki.

**Comment by fzipi** [comment]
@redRolf Can you take a look at the linked PR and see if it works for you?

**Comment by redRolf** [comment]
@fzipi Wow that was quick, I barely got coffee in that time 😍  Yes the changes work for me. Thank you for the quick help :)

**Comment by fzipi** [comment]
Thanks!
